### ISSUE TITLE
Can not compile with varnish 6.1

### ISSUE THREAD

**Issue by chrisLeeTW** [Gandi/libvmod-unidirectors#1]
Can not compile with varnish 6.1 & here is error logs.

```unidirectors.c  -fPIC -DPIC -o .libs/vmod_unidirectors.o
vmod_unidirectors.c: In function ‘vmod_find_backend’:
vmod_unidirectors.c:56:25: error: ‘const struct vdi_methods’ has no member named ‘find’; did you mean ‘finish’?
  if (be->vdir->methods->find)
                         ^~~~
                         finish
vmod_unidirectors.c:57:36: error: ‘const struct vdi_methods’ has no member named ‘find’; did you mean ‘finish’?
         return (be->vdir->methods->find(be, sa, VSA_Compare_IP));
                                    ^~~~
                                    finish
```

**Comment by chrisLeeTW** [comment]
and  here is my compile scripts with os ubuntu 18.04

```curl -s https://packagecloud.io/install/repositories/varnishcache/varnish61/script.deb.sh | bash && \
install_clean varnish varnish-dev && \
install_clean git-core build-essential libtool automake python-docutils && \
cd /tmp && \
git clone https://github.com/Gandi/libvmod-unidirectors.git && \
cd libvmod-unidirectors/ && \
./autogen.sh && \
./configure && \
make
```

**Comment by ehocdet** [comment]
@chrisLeeTW 
You need to used https://github.com/ehocdet/varnish-cache/tree/6.1-unidirector for full features.
Vmod-unidirectors for legacy varnish 6.1 is not pushed.
